services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${NEXT_PUBLIC_EMAILJS_SERVICE_ID}
        NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}
        NEXT_PUBLIC_EMAILJS_USER_ID: ${NEXT_PUBLIC_EMAILJS_USER_ID}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASS: ${SMTP_PASS}
    container_name: portfolio-app
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      gateway_net:
        aliases:
          - portfolio

networks:
  gateway_net:
    external: true
