import { Geist, Geist_Mono } from "next/font/google";
import Script from 'next/script';
import "@/index.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <Script src="https://kit.fontawesome.com/87293197e8.js" crossOrigin="anonymous" strategy="lazyOnload" />
      </body>
    </html>
  );
}
